### ISSUE TITLE
Layout Settings for All Artboards doesn't work

### ISSUE THREAD

**Issue by chhuang** [exevil/sketch-grid-master#2]
It only updates the layout for the current artboard.

**Comment by exevil** [comment]
@chhuang: Hey!

Sorry for the delay. Just checked, you can now assign grid and layout for for all artboards when you hit regular `View → Canvas → Grid/Layout Settings...` from the app menu with no artboard selected. 

Threrefore I'll remove this functionality from the plugin in next commit.

Thanks anyway! 👍
